area:reader:
  - '/(### (影响区域|相关区域)\r?\n\r?\n阅读器[ \t]*\r?$)/m'
area:book-source:
  - '/(### (影响区域|相关区域)\r?\n\r?\n书源[ \t]*\r?$)/m'
area:bookshelf:
  - '/(### (影响区域|相关区域)\r?\n\r?\n书架[ \t]*\r?$)/m'
area:rss:
  - '/(### (影响区域|相关区域)\r?\n\r?\n订阅\/RSS[ \t]*\r?$)/m'
area:manga:
  - '/(### (影响区域|相关区域)\r?\n\r?\n漫画[ \t]*\r?$)/m'
area:audio:
  - '/(### (影响区域|相关区域)\r?\n\r?\n音频[ \t]*\r?$)/m'
area:data:
  - '/(### (影响区域|相关区域)\r?\n\r?\n数据\/同步[ \t]*\r?$)/m'
area:build:
  - '/(### (影响区域|相关区域)\r?\n\r?\n构建\/安装[ \t]*\r?$)/m'
impact:crash:
  - '/(### 影响程度\r?\n\r?\n崩溃\/无法启动[ \t]*\r?$)/m'
impact:data-loss:
  - '/(### 影响程度\r?\n\r?\n数据丢失或损坏[ \t]*\r?$)/m'
impact:performance:
  - '/(### 影响程度\r?\n\r?\n性能问题[ \t]*\r?$)/m'
impact:compatibility:
  - '/(### 影响程度\r?\n\r?\n兼容性问题[ \t]*\r?$)/m'
impact:ui:
  - '/(### 影响程度\r?\n\r?\n界面异常[ \t]*\r?$)/m'
impact:functional:
  - '/(### 影响程度\r?\n\r?\n功能异常[ \t]*\r?$)/m'
