import { folderList } from '../componets/dataList/folderList'

export const novelPageList:folderList[] = [
  new folderList(1,'玄幻',12,$r('app.media.folder_test'),'玄幻','宿命之环等3本有更新',true),
  new folderList(2,'都市',13,$r('app.media.folder_test'),'都市'),
  new folderList(3,'仙侠',12,$r('app.media.folder_test'),'仙侠'),
  new folderList(4,'武侠',12,$r('app.media.folder_test'),'武侠'),
  new folderList(5,'奇幻',12,$r('app.media.folder_test'),'奇幻'),
  new folderList(6,'科幻',12,$r('app.media.folder_test'),'科幻'),
  new folderList(7,'历史',12,$r('app.media.folder_test'),'历史'),
  new folderList(8,'游戏',12,$r('app.media.folder_test'),'游戏'),
  new folderList(9,'悬疑',12,$r('app.media.folder_test'),'悬疑')
]