import { folderList } from '../componets/dataList/folderList'

export const novelPageList:folderList[] = [
  new folderList('玄幻',12,$r('app.media.folder_test'),'玄幻'),
  new folderList('都市',13,$r('app.media.folder_test'),'都市'),
  new folderList('仙侠',12,$r('app.media.folder_test'),'仙侠'),
  new folderList('武侠',12,$r('app.media.folder_test'),'武侠'),
  new folderList('奇幻',12,$r('app.media.folder_test'),'奇幻'),
  new folderList('科幻',12,$r('app.media.folder_test'),'科幻'),
  new folderList('历史',12,$r('app.media.folder_test'),'历史'),
  new folderList('游戏',12,$r('app.media.folder_test'),'游戏'),
  new folderList('悬疑',12,$r('app.media.folder_test'),'悬疑')
]