/**
 * @author 2008
 * @datetime 2024/6/28 22:29
 * @className: FontConstants
 * 通用字体大小样式
 */
export default class FontConstants{
  //字体大小
  static readonly FONT_SIZE_12: number = 12;
  static readonly FONT_SIZE_14: number = 14;
  static readonly FONT_SIZE_16: number = 16;
  static readonly FONT_SIZE_18: number = 18;
  static readonly FONT_SIZE_20: number = 20;
  static readonly FONT_SIZE_22: number = 22;
  static readonly FONT_SIZE_24: number = 24;
  //字体粗细
  static readonly FONT_WEIGHT_400: number = 400;
  static readonly FONT_WEIGHT_500: number = 500;
  static readonly FONT_WEIGHT_600: number = 600;
  static readonly FONT_WEIGHT_700: number = 700;
  static readonly FONT_WEIGHT_800: number = 800;
}