/**
 * @author 2008
 * @datetime 2024/6/28 22:34
 * @className: ImageConstants
 * 通用图片属性
 */
export default class ImageConstants{
  //图片宽度
  static readonly IMG_WIDTH_18: number = 18;
  static readonly IMG_WIDTH_20: number = 20;
  static readonly IMG_WIDTH_24: number = 24;
  static readonly IMG_WIDTH_32: number = 32;
  static readonly IMG_WIDTH_40: number = 40;
  static readonly IMG_WIDTH_48: number = 48;
  static readonly IMG_WIDTH_124: number = 124;

  //图片高度
  static readonly IMG_HEIGHT_18: number = 18;
  static readonly IMG_HEIGHT_20: number = 20;
  static readonly IMG_HEIGHT_24: number = 24;
  static readonly IMG_HEIGHT_32: number = 32;
  static readonly IMG_HEIGHT_40: number = 40;
  static readonly IMG_HEIGHT_48: number = 48;
  static readonly IMG_HEIGHT_120: number = 120;
}