/**
 * @author 2008
 * @datetime 2024/6/28 23:00
 * @className: PaddingConstants
 * padding/margin常量
 */
export default class PaddingConstants{
  static readonly PADDING_1:number = 1
  static readonly PADDING_2:number = 2
  static readonly PADDING_3:number = 3
  static readonly PADDING_4:number = 4
  static readonly PADDING_5:number = 5
  static readonly PADDING_6:number = 6
  static readonly PADDING_8:number = 8
  static readonly PADDING_9:number = 9
  static readonly PADDING_10:number = 10
  static readonly PADDING_11:number = 11
  static readonly PADDING_12:number = 12
  static readonly PADDING_13:number = 13
  static readonly PADDING_14:number = 14
  static readonly PADDING_15:number = 15
  static readonly PADDING_16:number = 16
  static readonly PADDING_17:number = 17
  static readonly PADDING_18:number = 18
  static readonly PADDING_19:number = 19
  static readonly PADDING_20:number = 20
  static readonly PADDING_21:number = 21
  static readonly PADDING_22:number = 22
  static readonly PADDING_24:number = 24
  static readonly PADDING_32:number = 32

}