
export const enum PublicConstants {

  //窗口背景色
  WINDOW_BACKGROUND_COLOR="rgba(245, 245, 245, 1)",
  //整体主题颜色
  THEME_COLOR="#F60",

  THEME_COLOR_WHITE="#ffffff"

}
export const enum TextConstants {

  //导航栏标题字体大小
  TITLE_FONT_SIZE="16",
  //导航栏标题字体行高
  TITLE_LINE_HEIGHT="24",
  //字体大小
  TEXT_FONT_SIZE="14",
  //字体行高
  TEXT_LINE_HEIGHT="22",

  TEXT_FONT_COLOR="rgba(0, 0, 0, 0.45)"
}



export const enum ImageConstants {

  icon=24
}

