/**
 * @author 2008
 * @datetime 2024/6/28 22:36
 * @className: TextConstants
 */
export default class TextConstants {
  //文本LinHeight高度
  static readonly TEXT_LINE_HEIGHT_18: number = 18;
  static readonly TEXT_LINE_HEIGHT_20: number = 20;
  static readonly TEXT_LINE_HEIGHT_22: number = 22;
  static readonly TEXT_LINE_HEIGHT_24: number = 24;
  static readonly TEXT_LINE_HEIGHT_26: number = 26;
  static readonly TEXT_LINE_HEIGHT_28: number = 28;
}