name: Triage issue labels

on:
  issues:
    types: [opened, edited]

permissions:
  contents: read
  issues: write

jobs:
  label:
    runs-on: ubuntu-latest
    steps:
      - name: Apply labels from issue text
        uses: github/issue-labeler@c1b0f9f52a63158c4adc09425e858e87b32e9685 # v3.4
        with:
          configuration-path: .github/issue-labeler.yml
          enable-versioned-regex: 0
          include-title: 0
          sync-labels: 1
          not-before: '2026-08-21T04:16:50Z'
          repo-token: ${{ github.token }}
